### PR TITLE
VG-4874 - Homepage Tests

### PR DESCRIPTION
**Pull request by gabrielthomasjacobs**
Added Home Page Tests
Added 2 methods to Util

### CODE REVIEW

**Comment by jdeolive** [comment]
Once this gets merged you'll want to update the job config here: https://jenkins.voyagerdev.com/view/test/job/navigo-test-main to include the home-spec.js file.

**Comment by gabrielthomasjacobs** [comment]
We added a new job at https://jenkins.voyagerdev.com/view/test/job/navigo-test-homepage/ to run the tests.

**Comment by jdeolive** [comment]
@gabrielthomasjacobs @scottlepp Does this spec need a special configuration? If not I suggest you guys just add it to the "main" job that is already there since adding a new job means we need to setup a time for it to run, etc... so that it doesn't conflict with the other integration tests, etc...

**Comment by scottlepp** [comment]
@jdeolive there's no special config.  Just trying to run these tests separately by feature so they can run in parallel/faster.   Do they conflict if they run at the same time?

**Comment by jdeolive** [comment]
@scottlepp Not sure, can you run multiple instances of selenium/chromedriver at the same time without having them trip over one another? If not then I don't think there is much benefit to trying to parallelize them. Plus they run nightly and not continuously so I don't think it's that much of a concern. A job per spec seems excessive from a jenkins maintenance standpoint too. I think we should only separate out "large specs" as separate jobs, like we have done with the processing one. But for smaller ones I prefer we keep it as part of the "main" job.

**Comment by scottlepp** [comment]
@jdeolive I assume you can, since you can configure a single one with multicapabilities.

The idea is job per top level feature (homepage, search, tasks, saved search) which seem like "large specs" since there are a lot of scenarios in each of those features.  The thought behind splitting by feature is that you can quickly see what feature is failing.  That's hard to determine if it's all in one big test.  And over time scenarios/tests within those features will grow.  This homepage spec isn't done, there are more scenarios to hit.

**Comment by jdeolive** [comment]
I get the idea, I just don't think it's practical. Each of those jobs duplicates configuration which is always error prone. As the person who maintains jenkins and who gets tapped when things "don't work" I don't feel like maintain 10 copies of the same job config. 

From what I have seen from the other test specs tests don't get added to them very quickly and they seem to remain constant size after a handful of tests are written for them. So how about when we get to the point where the homepage spec is "too large" we add it as a separate job but for now *please* put it in main.

**Pull request merged**
