### PR TITLE
Add a config.override.js file to customize config.js.

### PR DESCRIPTION
**Pull request by jdeolive**
Allows for customization without modifying files that are under version control.

### CODE REVIEW

**Comment by jdeolive** [comment]
@scottlepp Something for you to consider when you have some down time. I've always found it a bit cumbersome to have to edit a file under version control in order to set up a local dev environment. Prevents the one liner stage/commit everything.

**Comment by scottlepp** [comment]
Sorry @jdeolive  I know this is old.  Wouldn't this result in a 404 (behind the scenes) since config.override.js isn't included in the build?  I think we would need a grunt task to remove config.override.js from index.html?

**Comment by jdeolive** [comment]
Yeah, it would 404. I was thinking if we didn't like that I would just add an endpoint on the server that would handle that and return some empty content. Anyways, feel free to close this if you don't think it's of use... i definitely don't do front-end development enough to make this a real concern :)

**Comment by scottlepp** [comment]
It's definitely useful.  It should be fairly simple to create a grunt task
to remove the override.js from index.html during the build.

On Thu, Apr 14, 2016 at 2:49 PM, Justin Deoliveira <notifications@github.com

**Pull request closed without merging**
